CREATE TABLE IF NOT EXISTS public.criteria (
  id bigint generated by default as identity not null,
  parameter text not null,
  operator text not null,
  criteria_value numeric not null,
  percent_value numeric null default 0,
  constraint criteria_pkey primary key (id)
) TABLESPACE pg_default;

INSERT INTO public.criteria (parameter, operator, criteria_value, percent_value)
SELECT seed.parameter, seed.operator, seed.criteria_value, 0
FROM (VALUES
  ('MIC', '<', 3.9::numeric),
  ('UHML', '<', 28.5::numeric),
  ('UI', '<', 80::numeric),
  ('STR', '<', 28.5::numeric),
  ('SFI', '>', 9.0::numeric),
  ('Rd', '<', 75::numeric),
  ('+b', '>', 10.0::numeric)
) AS seed(parameter, operator, criteria_value)
WHERE NOT EXISTS (
  SELECT 1
  FROM public.criteria existing
  WHERE existing.parameter = seed.parameter
);